#!/bin/sh /etc/rc.common

START=99

start() {
	if [ -x /usr/sbin/wifi_schedule ]
	then
		if [ -f /var/run/wifi_schedule.pid ] && [ "$(cat /var/run/wifi_schedule.pid)" -gt 0 ]
		then
			logger "wifi_schedule is running with pid $(cat /var/run/wifi_schedule.pid)"
		else
			logger "wifi_schedule is starting"
			/usr/sbin/wifi_schedule &
		fi
	fi
}

stop () {
	[ -f /var/run/wifi_schedule.pid ] && kill -USR1 $(cat /var/run/wifi_schedule.pid) && rm /var/run/wifi_schedule.pid
	if [ "x$(uci -q -P /var/state/ get wireless.@wifi-iface[0].up)" != "x1" ]
	then
		logger "wifi_schedule is turning off and wifi is off, so turn it on"
		wifi up
	else
		logger "wifi_schedule is turning off"
	fi
}