#!/bin/sh /etc/rc.common

START=99

start() {
	if [ -x /usr/sbin/wifi_schedule ]
	then
		if [ -f /var/run/wifi_schedule.pid ] && [ "$(cat /var/run/wifi_schedule.pid)" -gt 0 ]
		then
			echo "wifi_schedule is running"
		else
                        echo "Starting wifi_schedule"
                        /usr/sbin/wifi_schedule &
		fi
	fi
}

stop () {
	[ -f /var/run/wifi_schedule.pid ] && kill $(cat /var/run/wifi_schedule.pid) && rm /var/run/wifi_schedule.pid
}
